volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres:11
    volumes:
      - ./postgres_data:/var/lib/postgresql:rw
    environment:
      POSTGRES_DB: sec
      POSTGRES_USER: secapp
      POSTGRES_PASSWORD: 1234
    ports:
      - 5433:5432
  app:
    # See ./Dockerfile
    image: sec_poc/r
    volumes:
      - ~/Desktop/sec_poc:/opt/R/sec_poc
    depends_on:
      - postgres
    ports:
      - 8888:8888
