@trial_id = NCT03621982

### Locating trials on my own
POST https://clinicaltrialsapi.cancer.gov/api/v2/trials
    accept: */*
    X-API-KEY: {{$processEnv CTS_V2_API_KEY}}

{
    "include": [
        "nct_id",
        "official_title",
        "brief_summary",
        "detail_description",
        "anatomic_sites",
        "diseases.name",
        "diseases.nci_thesaurus_concept_id",
        "diseases.inclusion_indicator"
    ],
    "anatomic_sites": ["Lung"],
    "official_title": "Metastatic",
    "official_title_not": "Stage",
    "from": 0,
    "size": 50
}

### Trials from Sandy
POST https://clinicaltrialsapi.cancer.gov/api/v2/trials
    accept: */*
    X-API-KEY: {{$processEnv CTS_V2_API_KEY}}

{
  "current_trial_status": [
    "Active",
    "Approved",
    "Enrolling by Invitation",
    "In Review",
    "Temporarily Closed to Accrual",
    "Temporarily Closed to Accrual and Intervention"
  ],
  "include": [
    "nct_id",
    "official_title",
    "brief_summary",
    "detail_description",
    "anatomic_sites",
    "diseases.name",
    "diseases.nci_thesaurus_concept_id",
    "diseases.inclusion_indicator"
  ],
  "maintype": ["C2926"],
  "subtype": ["C156094"],
  "primary_purpose": ["treatment"],
  "from": 0,
  "size": 50
}

### A specific trial to debug
POST https://clinicaltrialsapi.cancer.gov/api/v2/trials
    accept: */*
    X-API-KEY: {{$processEnv CTS_V2_API_KEY}}

{
    "include": [
        "nct_id",
        "official_title",
        "brief_summary",
        "detail_description",
        "anatomic_sites",
        "diseases.name",
        "diseases.nci_thesaurus_concept_id",
        "diseases.inclusion_indicator",
        "primary_purpose"
    ],
    "nct_id": "NCT03586453",
    "size": 1
}
