services:
  shiny:
    image: sec_poc_prod:latest
    ports:
      - 3838:3838
    env_file:
      - .env.stage
    volumes:
      - ./shiny-server-logs:/var/log/shiny-server
  postgres:
    image: postgres:16
    ports:
      - 5434:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - sec_poc_stage_db:/var/lib/postgresql/data

volumes:
  sec_poc_stage_db:
    external: true
