[project]
name = "sec-poc"
version = "0.1.0"
description = "A monorepo of various demos/"
requires-python = ">=3.9"
dependencies = []

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
]

[tool.uv.workspace]
members = ["demos/ctsapi_for_public_use"]
