[project]
name = "sec-poc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
    "pandas>=2.3.1",
    "streamlit>=1.46.1",
]
