###
GET https://www.cancer.gov/cts_api/zip_code_lookup/28502

###
@from = 0
@size = 10
POST https://clinicaltrialsapi.cancer.gov/api/v2/trials
x-api-key: {{$processEnv CTS_V2_API_KEY}}

{
    "include": [
        #// "lead_org",
        #// "sites.contact_email",
        #// "sites.org_state_or_province",
        #// "current_trial_status",
        #// "ccr_id",
        "nct_id",
        "amendment_date"
        #// "protocol_id",
        #// "study_source",
        #// "nci_funded",
        #// "ctep_id",
        #// "sites.recruitment_status"
        #// "sites"
    ],

    #// "current_trial_status": "Enrolling by Invitation",
    #// "sites.recruitment_status": "APPROVED",

    #// "sites.org_state_or_province": "VA",
    #// "sites.contact_email": "Charmaine.A.Mckie@kp.org",

    #// "current_trial_status_date": [
    #//     "2023-08-31",
    #//     "2022-06-16"
    #// ],

    #// "lead_org._raw": "National Cancer Institute",
    #// "lead_org._raw": "NCI - Center for Cancer Research",

    #// "nci_funded_not": "Direct",
    #// "study_source_not": "Institutional",

    #// "missing_not": ["ctep_id"],
    #// "nci_funded": "Direct",
    #// "study_source": "National",
    #// "outer_or_lead_org._fulltext": "NCI",
 
    "current_trial_status": [
        "Active",
        "Approved",
        "Enrolling by Invitation",
        "Temporarily Closed to Accrual",
        "Temporarily Closed to Accrual and Intervention"
    ],
    "from": {{from}},
    "size": {{size}}
}

### ClinicalTrials.gov API
@study = NCT05879926
GET https://clinicaltrials.gov/api/v2/studies/{{study}}?format=json&fields=EligibilityModule
