services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: sec
      POSTGRES_USER: secapp
      POSTGRES_PASSWORD: 1234
    ports:
      - 5433:5432
    volumes:
      - sec_poc_pg:/var/lib/postgresql/data
  app:
    # See ./Dockerfile
    image: sec_poc/r
    volumes:
      - ~/Desktop/sec_poc_workspace:/opt/R/sec_poc_workspace
    depends_on:
      - postgres
    ports:
      - 8888:8888

volumes:
  sec_poc_pg:
    external: true
