require(devtools)

install_version('shiny', version = '1.4.0', repos = 'http://cran.us.r-project.org')
install_version('shinyBS', version = '0.61', repos = 'http://cran.us.r-project.org')
install_version('shinyFeedback', version = '0.2.0', repos = 'http://cran.us.r-project.org')
install_version('shinyWidgets', version = '0.5.0', repos = 'http://cran.us.r-project.org')
install_version('shinyalert', version = '2.0.0', repos = 'http://cran.us.r-project.org')
install_version('shinydashboard', version = '0.7.1', repos = 'http://cran.us.r-project.org')
install_version('shinyjs', version = '1.0', repos = 'http://cran.us.r-project.org')
install_version('shinymanager', version = '1.0.300', repos = 'http://cran.us.r-project.org')
install_version('shinythemes', version = '1.1.2', repos = 'http://cran.us.r-project.org')
