options(repos = c(CRAN = sprintf("https://packagemanager.posit.co/cran/latest/bin/linux/centos8-%s/%s", R.version["arch"], substr(getRversion(), 1, 3))))
# region RSQLite
pak::pkg_install("cran/glue@1.8.0", ask = FALSE)
pak::pkg_install("cran/cpp11@0.5.2", ask = FALSE)
pak::pkg_install("cran/RSQLite@2.4.5", ask = FALSE)
# endregion
# region devtools
pak::pkg_install("cran/downlit@0.4.5", ask = FALSE)
pak::pkg_install("cran/purrr@1.2.0", ask = FALSE)
pak::pkg_install("cran/pkgdown@2.2.0", ask = FALSE)
pak::pkg_install("cran/profvis@0.4.0", ask = FALSE)
pak::pkg_install("cran/waldo@0.6.2", ask = FALSE)
pak::pkg_install("cran/testthat@3.3.1", ask = FALSE)
pak::pkg_install("cran/httr2@1.2.2", ask = FALSE)
pak::pkg_install("cran/devtools@2.4.6", ask = FALSE)
# endregion
pak::pkg_install("cran/plyr@1.8.9", ask = FALSE)
pak::pkg_install("cran/htmlwidgets@1.6.4", ask = FALSE)
pak::pkg_install("cran/data.tree@1.2.0", ask = FALSE)
pak::pkg_install("cran/dplyr@1.1.4", ask = FALSE)
pak::pkg_install("cran/RColorBrewer@1.1-3", ask = FALSE)
pak::pkg_install("cran/colorspace@2.1-2", ask = FALSE)
pak::pkg_install("cran/httr@1.4.7", ask = FALSE)
pak::pkg_install("cran/data.table@1.18.0", ask = FALSE)
pak::pkg_install("cran/jsonlite@2.0.0", ask = FALSE)
pak::pkg_install("cran/openxlsx@4.2.8.1", ask = FALSE)
pak::pkg_install("cran/assertthat@0.2.1", ask = FALSE)
pak::pkg_install("cran/shiny@1.12.1", ask = FALSE)
pak::pkg_install("cran/DT@0.34.0", ask = FALSE)
pak::pkg_install("cran/DBI@1.2.3", ask = FALSE)
pak::pkg_install("cran/xtable@1.8-4", ask = FALSE)
pak::pkg_install("cran/gtable@0.3.6", ask = FALSE)
pak::pkg_install("cran/leaflet@2.2.3", ask = FALSE)
pak::pkg_install("cran/maps@3.4.3", ask = FALSE)
pak::pkg_install("cran/shinythemes@1.2.0", ask = FALSE)
pak::pkg_install("cran/shinydashboard@0.7.3", ask = FALSE)
pak::pkg_install("cran/shinyjs@2.1.0", ask = FALSE)
pak::pkg_install("cran/sqldf@0.4-11", ask = FALSE)
pak::pkg_install("cran/shinyWidgets@0.9.0", ask = FALSE)
pak::pkg_install("cran/stringi@1.8.7", ask = FALSE)
pak::pkg_install("cran/datawizard@1.3.0", ask = FALSE)
pak::pkg_install("cran/sjmisc@2.8.11", ask = FALSE)
pak::pkg_install("cran/shinyBS@0.63.0", ask = FALSE)
pak::pkg_install("cran/collapsibleTree@0.1.8", ask = FALSE)
pak::pkg_install("cran/lubridate@1.9.4", ask = FALSE)
pak::pkg_install("cran/shinyFeedback@0.4.0", ask = FALSE)
pak::pkg_install("cran/parsedate@1.3.2", ask = FALSE)
pak::pkg_install("cran/reticulate@1.44.1", ask = FALSE)
pak::pkg_install("cran/pool@1.0.4", ask = FALSE)
pak::pkg_install("cran/shinyalert@3.1.0", ask = FALSE)
pak::pkg_install("cran/RPostgres@1.4.8", ask = FALSE)
pak::pkg_install("cran/stringr@1.6.0", ask = FALSE)
pak::pkg_install("cran/shinymanager@1.0.410", ask = FALSE)
pak::pkg_install("cran/writexl@1.5.4", ask = FALSE)
pak::pkg_install("cran/config@0.3.2", ask = FALSE)