name: Build images

on:
  push:
    branches: [$default-branch]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout SEC POC docker branch

      - uses: actions/checkout@v4
        name: Checkout SEC POC main branch
        with:
          ref: ${{ github.event.repository.default_branch }}
          path: sec_poc

      - uses: actions/checkout@v4
        name: Checkout the SEC Admin
        with:
          repository: CBIIT/sec_admin
          path: sec_admin
          ref: cloud-migration

      - uses: actions/checkout@v4
        name: Checkout the SEC NLP
        with:
          repository: CBIIT/sec_nlp
          path: sec_nlp

      - uses: docker/setup-qemu-action@v3
        name: Set up QEMU

      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - uses: actions/cache@v3
        name: Save/Restore Cache
        id: cache
        with:
          path: |
            renv-cache
            renv-cache-shiny
            pip-cache
          key: cache-${{ hashFiles('sec_poc/renv.lock', 'sec_admin/renv.lock', 'sec_nlp/requirements.txt') }}

      - uses: reproducible-containers/buildkit-cache-dance@v3.1.0
        name: Inject Cache Into Docker
        with:
          cache-map: |
            {
              "renv-cache": "/root/.cache/R/renv",
              "renv-cache-shiny": "/home/shiny/.cache/R/renv",
              "pip-cache": "/root/.cache/pip"
            }
          skip-extraction: ${{ steps.cache.outputs.cache-hit }}

      - uses: docker/build-push-action@v6
        name: Build Dev Container
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max,scope=dev
          context: .
          file: Dockerfile.dev
          outputs: type=docker,tar=true,dest=sec_poc_dev.tar
          platforms: linux/amd64,linux/arm64
          push: false
          tags: sec_poc_dev:latest

      - uses: docker/build-push-action@v6
        name: Build ETL Container
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max,scope=etl
          context: .
          file: Dockerfile.ETL
          outputs: type=docker,tar=true,dest=sec_poc_etl.tar
          platforms: linux/amd64,linux/arm64
          push: false
          tags: sec_poc_etl:latest

      - uses: docker/build-push-action@v6
        name: Build Prod Container
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max,scope=prod
          context: .
          file: Dockerfile.prod
          outputs: type=docker,tar=true,dest=sec_poc_prod.tar
          platforms: linux/amd64
          push: false
          tags: sec_poc_prod:latest

      - uses: actions/upload-artifact@v4
        with:
          name: docker-images
          path: sec_poc_*.tar
          retention-days: 7
